import xml.etree.ElementTree as ET
import re

def get_LNCELS(XMLroot, mrbtsId):
    lcr = []
    for cmData in XMLroot:
        for managedObject in cmData:
            if (managedObject.attrib.get('class') == 'LNCEL' and (("/MRBTS-"+ str(mrbtsId)) in managedObject.attrib.get('distName')) ):
                for data in managedObject:
                    if (data.attrib.get('name') == 'lcrId'):
                        lcr.append(data.text)
    return lcr

def is_ValidMRBTS(XMLroot, line):
    for cmData in XMLroot:
        for managedObject in cmData:
            if (managedObject.attrib.get('class') == 'LNCEL' and (("/MRBTS-"+ str(line)) in managedObject.attrib.get('distName')) ):
                return True

filename1 = input("Enter XML filename: ") + '.xml' ## File from NetACT exports
filename2 = input("Enter TXT filename: ") + '.txt' ## File from planning
net_MCC = (input("Enter destination MCC: ") or "278") ## default 278
net_MNC = (input("Enter destination MNC: ") or "01") ## default 01
net_NMSIP = (input("Enter NMS IP: ") or "192.168.63.33") ## default 192.168.63.33
net_TCEIP = (input("Enter 3rd Party trace collection entity IP: ") or "10.215.192.7") ## default 10.215.192.7

XMLroot = ET.parse(filename1).getroot()
txtLines = open(filename2, 'r')
generatedXML = '<?xml version="1.0"?><raml xmlns="raml21.xsd" version="2.1"><cmData type="plan" scope="all" name="cell_tracing">'

for line in txtLines:
    mrbtsId = line.strip()
    if(is_ValidMRBTS(XMLroot, mrbtsId)):
        print('Generating script for MRBTS-' + mrbtsId)
        siteId = int(mrbtsId[2:])
        
        # Create LNBTS
        generatedXML += '<managedObject class="LNBTS" distName="PLMN-PLMN/MRBTS-' + mrbtsId + '/LNBTS-' + mrbtsId + '">'
        generatedXML += '<p name="actCellTrace">true</p>'
        generatedXML += '<p name="actMDTCellTrace">true</p>'
        generatedXML += '<p name="actInterFreqMDTCellTrace">true</p>'
        generatedXML += '<p name="actMDTloggedCellTrace">true</p>'
        generatedXML += '<p name="actUeThroughputMeas">true</p>'
        generatedXML += '<p name="actVendSpecCellTraceEnh">true</p>'
        generatedXML += '</managedObject>'
        
        # Create CTRLTS
        generatedXML += '<managedObject class="CTRLTS" distName="PLMN-PLMN/MRBTS-' + mrbtsId + '/LNBTS-' + mrbtsId + '/CTRLTS-1">'
        generatedXML += '<defaults name="System"/>'
        generatedXML += '<p name="extCellTraceRep">true</p>'
        generatedXML += '<p name="extUeTraceRep">true</p>'
        generatedXML += '<p name="maxUeTraceSessions">60</p>'
        generatedXML += '<p name="netActIpAddr">' + net_NMSIP + '</p>'
        generatedXML += '<p name="omsTracePortNum">49392</p>'
        generatedXML += '<p name="subscriberMDTObtainLocation">false</p>'
        generatedXML += '<list name="tceIdLogMdtIpMap">'
        generatedXML += '<item>'
        generatedXML += '<p name="loggedPortNum">49151</p>'
        generatedXML += '<p name="loggedTCEIP">' + net_TCEIP + '</p>'
        generatedXML += '<p name="loggedTCEId">1</p>'
        generatedXML += '<p name="loggedTCEmcc">'+ net_MCC +'</p>'
        generatedXML += '<p name="loggedTCEmnc">'+ net_MNC +'</p>'
        generatedXML += '<p name="loggedTCEmncLen">'+ str(len(net_MNC)) +'</p>'
        generatedXML += '</item>'
        generatedXML += '</list>'
        generatedXML += '<p name="tceTracePortNum">49151</p>'
        generatedXML += '<p name="cellTraceRepMode">Online</p>'
        generatedXML += '<p name="ueTraceRepMode">Online</p>'
        generatedXML += '<p name="taTracing">true</p>'
        generatedXML += '</managedObject>'
        
        cellCount = 0
        for lncel in get_LNCELS(XMLroot, mrbtsId):
            cellCount += 1
            
            # Create MTRACE
            generatedXML += '<managedObject class="MTRACE" distName="PLMN-PLMN/MRBTS-' + mrbtsId + '/LNBTS-' + mrbtsId + '/CTRLTS-1/MTRACE-' + str(cellCount) + '">'
            generatedXML += '<p name="eutranTraceIdMcc">'+ net_MCC +'</p>'
            generatedXML += '<p name="eutranTraceIdMnc">'+ net_MNC +'</p>'
            generatedXML += '<p name="traceId">'+ str(siteId) + lncel + '</p>'
            generatedXML += '<p name="trcRecSessionRef">65535</p>'
            generatedXML += '<p name="actUeThroughputMR">true</p>'
            generatedXML += '<p name="cellMaxActiveUEsTraced">10000</p>'
            generatedXML += '<p name="cellTrcMode">true</p>'
            generatedXML += '<p name="cellTaTracing">true</p>'
            generatedXML += '<p name="aoATracing">false</p>'
            generatedXML += '<p name="pDSCHPRBNumberTracing">true</p>'
            generatedXML += '<p name="pHRTracing">true</p>'
            generatedXML += '<p name="pUSCHPRBNumberTracing">true</p>'
            generatedXML += '<p name="ripTracing">false</p>'
            generatedXML += '<p name="tATracingSynch">false</p>'
            generatedXML += '<p name="uEBSRTracing">true</p>'
            generatedXML += '<p name="uERankTracing">true</p>'
            generatedXML += '<p name="uLSINRTracing">true</p>'
            generatedXML += '<p name="cellMaxActiveMDTUEsTraced">100</p>'
            generatedXML += '<p name="immedMDTAnonymization">IMEI-TAC</p>'
            generatedXML += '<p name="immedMDTForceUEConsent">true</p>'
            generatedXML += '<p name="immedMDTObtainLocation">true</p>'
            generatedXML += '<p name="immedMDTPosMethod">GNSS</p>'
            generatedXML += '<p name="immedMDTSelectOnlyGNSSUes">false</p>'
            generatedXML += '<p name="jobType">ImmediateMDTAndTrace</p>'
            generatedXML += '<p name="lcrId">' + lncel + '</p>'
            generatedXML += '<p name="maxBufferingTime">2000</p>'
            generatedXML += '<p name="reportAmount">infinity</p>'
            generatedXML += '<p name="reportInterval">5120ms</p>'
            generatedXML += '<p name="tceCellTracePortNum">49151</p>'
            generatedXML += '<p name="tceIpAddress">' + net_TCEIP + '</p>'
            generatedXML += '<p name="actPCMDReporting">false</p>'
            generatedXML += '<list name="traceRrcNonUeSpecMsgList">'
            generatedXML += '<p>8193</p>'
            generatedXML += '<p>8194</p>'
            generatedXML += '<p>8192</p>'
            generatedXML += '</list>'
            generatedXML += '<p name="traceRrcSetting">All</p>'
            generatedXML += '<list name="traceRrcUeSpecMsgList">'
            generatedXML += '<p>262</p>'
            generatedXML += '<p>20</p>'
            generatedXML += '<p>261</p>'
            generatedXML += '<p>21</p>'
            generatedXML += '<p>263</p>'
            generatedXML += '<p>22</p>'
            generatedXML += '<p>266</p>'
            generatedXML += '<p>24</p>'
            generatedXML += '<p>516</p>'
            generatedXML += '<p>15</p>'
            generatedXML += '<p>14</p>'
            generatedXML += '<p>17</p>'
            generatedXML += '<p>518</p>'
            generatedXML += '<p>19</p>'
            generatedXML += '<p>18</p>'
            generatedXML += '<p>277</p>'
            generatedXML += '<p>276</p>'
            generatedXML += '<p>13</p>'
            generatedXML += '<p>11</p>'
            generatedXML += '<p>10</p>'
            generatedXML += '<p>7</p>'
            generatedXML += '<p>9</p>'
            generatedXML += '<p>26</p>'
            generatedXML += '<p>278</p>'
            generatedXML += '<p>25</p>'
            generatedXML += '<p>521</p>'
            generatedXML += '<p>4</p>'
            generatedXML += '<p>5</p>'
            generatedXML += '<p>6</p>'
            generatedXML += '</list>'
            generatedXML += '<list name="traceS1NonUeSpecMsgList">'
            generatedXML += '<p>8235</p>'
            generatedXML += '<p>8226</p>'
            generatedXML += '<p>8193</p>'
            generatedXML += '<p>8209</p>'
            generatedXML += '<p>8227</p>'
            generatedXML += '<p>8228</p>'
            generatedXML += '<p>8229</p>'
            generatedXML += '<p>8238</p>'
            generatedXML += '<p>8239</p>'
            generatedXML += '<p>8733</p>'
            generatedXML += '<p>8734</p>'
            generatedXML += '<p>8232</p>'
            generatedXML += '<p>8721</p>'
            generatedXML += '<p>8233</p>'
            generatedXML += '<p>8221</p>'
            generatedXML += '<p>8230</p>'
            generatedXML += '<p>8222</p>'
            generatedXML += '<p>8477</p>'
            generatedXML += '<p>8478</p>'
            generatedXML += '<p>8465</p>'
            generatedXML += '<p>8491</p>'
            generatedXML += '<p>8462</p>'
            generatedXML += '<p>8206</p>'
            generatedXML += '<p>8484</p>'
            generatedXML += '</list>'
            generatedXML += '<p name="traceS1Setting">All</p>'
            generatedXML += '<list name="traceS1UeSpecMsgList">'
            generatedXML += '<p>260</p>'
            generatedXML += '<p>44</p>'
            generatedXML += '<p>45</p>'
            generatedXML += '<p>262</p>'
            generatedXML += '<p>20</p>'
            generatedXML += '<p>261</p>'
            generatedXML += '<p>21</p>'
            generatedXML += '<p>263</p>'
            generatedXML += '<p>22</p>'
            generatedXML += '<p>23</p>'
            generatedXML += '<p>24</p>'
            generatedXML += '<p>42</p>'
            generatedXML += '<p>265</p>'
            generatedXML += '<p>513</p>'
            generatedXML += '<p>515</p>'
            generatedXML += '<p>512</p>'
            generatedXML += '<p>15</p>'
            generatedXML += '<p>533</p>'
            generatedXML += '<p>16</p>'
            generatedXML += '<p>19</p>'
            generatedXML += '<p>18</p>'
            generatedXML += '<p>0</p>'
            generatedXML += '<p>31</p>'
            generatedXML += '<p>2</p>'
            generatedXML += '<p>277</p>'
            generatedXML += '<p>32</p>'
            generatedXML += '<p>33</p>'
            generatedXML += '<p>13</p>'
            generatedXML += '<p>12</p>'
            generatedXML += '<p>11</p>'
            generatedXML += '<p>7</p>'
            generatedXML += '<p>28</p>'
            generatedXML += '<p>8</p>'
            generatedXML += '<p>27</p>'
            generatedXML += '<p>26</p>'
            generatedXML += '<p>9</p>'
            generatedXML += '<p>521</p>'
            generatedXML += '<p>279</p>'
            generatedXML += '<p>25</p>'
            generatedXML += '<p>3</p>'
            generatedXML += '<p>4</p>'
            generatedXML += '<p>259</p>'
            generatedXML += '<p>256</p>'
            generatedXML += '<p>5</p>'
            generatedXML += '<p>257</p>'
            generatedXML += '<p>6</p>'
            generatedXML += '</list>'
            generatedXML += '<list name="traceX2NonUeSpecMsgList">'
            generatedXML += '<p>8198</p>'
            generatedXML += '<p>8199</p>'
            generatedXML += '<p>8193</p>'
            generatedXML += '<p>8194</p>'
            generatedXML += '<p>8456</p>'
            generatedXML += '<p>8457</p>'
            generatedXML += '<p>8454</p>'
            generatedXML += '<p>8710</p>'
            generatedXML += '<p>8455</p>'
            generatedXML += '<p>8712</p>'
            generatedXML += '<p>8713</p>'
            generatedXML += '<p>8200</p>'
            generatedXML += '<p>8716</p>'
            generatedXML += '<p>8192</p>'
            generatedXML += '<p>8206</p>'
            generatedXML += '<p>8205</p>'
            generatedXML += '<p>8204</p>'
            generatedXML += '<p>8460</p>'
            generatedXML += '<p>8202</p>'
            generatedXML += '<p>8201</p>'
            generatedXML += '</list>'
            generatedXML += '<p name="traceX2Setting">All</p>'
            generatedXML += '<list name="traceX2UeSpecMsgList">'
            generatedXML += '<p>1</p>'
            generatedXML += '<p>3</p>'
            generatedXML += '<p>4</p>'
            generatedXML += '<p>512</p>'
            generatedXML += '<p>256</p>'
            generatedXML += '<p>5</p>'
            generatedXML += '</list>'
            generatedXML += '</managedObject>'
            
            # Create LTRACE
            generatedXML += '<managedObject class="LTRACE" distName="PLMN-PLMN/MRBTS-' + mrbtsId + '/LNBTS-' + mrbtsId + '/CTRLTS-1/LTRACE-' + str(cellCount) + '">'
            generatedXML += '<p name="enableLoggedMdtTRSStartStopInd">true</p>'
            generatedXML += '<p name="lcrId">' + lncel + '</p>'
            generatedXML += '<p name="mode">configureAndRetrieveDataFromUEs</p>'
            generatedXML += '<p name="anonymizationMDTdata">No identity</p>'
            generatedXML += '<p name="forceUEconsent">true</p>'
            generatedXML += '<p name="loggedTCEId">0</p>'
            generatedXML += '<p name="loggingDuration">20</p>'
            generatedXML += '<p name="loggingInterval">5120</p>'
            generatedXML += '<p name="selectOnlyStandaloneGNSSUes">false</p>'
            generatedXML += '<p name="traceId">'+ str(siteId) + lncel + '</p>'
            generatedXML += '<p name="traceReferenceMcc">'+ net_MCC +'</p>'
            generatedXML += '<p name="traceReferenceMnc">'+ net_MNC +'</p>'
            generatedXML += '<p name="traceReferenceMncLen">'+ str(len(net_MNC)) +'</p>'
            generatedXML += '</managedObject>'   
    else:
        print('MRBTS-' + mrbtsId + ' is not valid, skipping')
generatedXML += '</cmData></raml>'        
with open("output.xml", "w") as f:
    f.write(generatedXML)